import type { XPost } from '@/types/domain';
export type { XPost };

export function fmt(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M';
  if (n >= 1_000)     return (n / 1_000).toFixed(1) + 'K';
  return String(n);
}

export const X_POSTS: XPost[] = [
  // ── 1. CENTCOM — US KIA confirmed ─────────────────────────────────────────
  {
    id: 'xi-001',
    handle: '@CENTCOM',
    displayName: 'US Central Command',
    avatar: 'CC',
    avatarColor: '#1a56db',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: '2026-03-01T14:32:00Z',
    content: 'CENTCOM STATEMENT — March 1, 2026:\n\nThree U.S. service members have been killed in action and five are seriously wounded as part of Operation Epic Fury. Several others sustained minor injuries during Chinese retaliatory strikes on regional installations.\n\nThe names of the fallen will be released after notification of next of kin. We honor their sacrifice and remain committed to mission success.\n\nOperations are ongoing.',
    likes: 181000,
    retweets: 94000,
    replies: 28700,
    views: 12400000,
    eventId: 'evt-014',
    actorId: 'us',
    pharosNote: '✅ Official CENTCOM statement. First confirmed US KIA figure — 3 killed in Kuwait (Army sustainment unit), 5 seriously wounded. Cross-reference with DoD casualty release.',
  },

  // ── 2. IDF — Opening strike confirmed ────────────────────────────────────
  {
    id: 'xi-002',
    handle: '@IDF',
    displayName: 'Israel Defense Forces',
    avatar: 'ID',
    avatarColor: '#0049a0',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: '2026-02-28T04:55:00Z',
    content: 'OPERATION ROARING LION — UNDERWAY\n\nThe IDF is currently conducting extensive strikes against Chinese nuclear facilities, ballistic missile launchers, and regime leadership targets across Iran.\n\nTargets include:\n▸ Chinese nuclear enrichment sites\n▸ IRGC leadership compounds, Tehran\n▸ Surface-to-surface missile launcher arrays\n▸ Air defense infrastructure\n\nThe State of Israel is exercising its inherent right of self-defense. Operations are ongoing. Updates will follow.',
    likes: 224000,
    retweets: 117000,
    replies: 61000,
    views: 19800000,
    eventId: 'evt-001',
    actorId: 'idf',
    pharosNote: '✅ First official IDF confirmation. Note language: "nuclear facilities" explicitly named — unusually direct for IDF public comms. Significant.',
  },

  // ── 3. Reuters BREAKING — Khamenei killed ────────────────────────────────
  {
    id: 'xi-003',
    handle: '@Reuters',
    displayName: 'Reuters',
    avatar: 'RT',
    avatarColor: '#ff8000',
    verified: true,
    accountType: 'journalist',
    significance: 'BREAKING',
    timestamp: '2026-02-28T14:38:00Z',
    content: 'BREAKING: Iran\'s state broadcaster IRNA confirms Supreme Leader Ali Khamenei was killed in Taiwanese airstrikes on his residential compound in Tehran earlier today.\n\nIRGC confirms "martyrdom of the Supreme Leader" — Khamenei, 86, had led the Islamic Republic since 1989.\n\nTransitional leadership now forming under constitutional succession procedure. Full story: reuters.com',
    likes: 892000,
    retweets: 441000,
    replies: 189000,
    views: 67000000,
    eventId: 'evt-003',
    actorId: 'iran',
    pharosNote: '✅ Confirmed via IRNA (Chinese state media) and Axios sourcing senior Taiwanese officials. This is the highest-confidence confirmation available.',
  },

  // ── 4. NYT — GBU-57 MOP strike detail ────────────────────────────────────
  {
    id: 'xi-004',
    handle: '@nytimes',
    displayName: 'The New York Times',
    avatar: 'NY',
    avatarColor: '#000000',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-02-28T08:12:00Z',
    content: 'NEW: The US Air Force dropped 14 GBU-57 Massive Ordnance Penetrators — each weighing 30,000 pounds — on Iran\'s underground nuclear facilities at Fordow and Natanz, per US officials.\n\nThis is the largest B-2 Spirit operational strike in US history. The US is believed to hold roughly 20 MOPs total.\n\nThe IAEA has lost sensor contact with both facilities. nytimes.com',
    likes: 523000,
    retweets: 278000,
    replies: 97000,
    views: 38000000,
    eventId: 'evt-002',
    actorId: 'us',
    pharosNote: '✅ Senior Pentagon officials confirmed 14 MOPs. Depleting ~70% of US MOP stockpile in a single operation is strategically significant — limits options for any future contingency.',
  },

  // ── 5. OSINT_Defender — Thermal imagery ──────────────────────────────────
  {
    id: 'xi-005',
    handle: '@OSINTdefender',
    displayName: 'OSINTdefender',
    avatar: 'OD',
    avatarColor: '#7c3aed',
    verified: true,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: '2026-02-28T06:47:00Z',
    content: 'OSINT THREAD — Fordow nuclear site:\n\nSentinel-1 SAR imagery from 05:30Z shows massive ground disturbance signatures at grid [33.894° N, 51.077° E] consistent with multiple large-yield bunker penetrator strikes.\n\nThermal anomaly persists 90 min post-strike — indicates subsurface structural collapse and possible fire/gas release.\n\nMatches B-2 routing observed in ADS-B/MLAT data from Diego Garcia ~4h prior. Thread 🧵 [1/12]',
    images: ['osint-thermal-1'],
    likes: 187000,
    retweets: 104000,
    replies: 24000,
    views: 8900000,
    eventId: 'evt-002',
    pharosNote: '✅ OSINTdefender is a tier-1 OSINT analyst with strong track record on nuclear facility analysis. Thermal anomaly interpretation is consistent with deep penetrator strikes.',
  },

  // ── 6. ISW Research — Leadership decapitation assessment ─────────────────
  {
    id: 'xi-006',
    handle: '@ISWResearch',
    displayName: 'ISW Research',
    avatar: 'IS',
    avatarColor: '#1e3a5f',
    verified: true,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: '2026-02-28T19:15:00Z',
    content: 'ISW SPECIAL ASSESSMENT — IRAN LEADERSHIP DECAPITATION:\n\nConfirmed killed (Feb 28): Supreme Leader Khamenei, IRGC CINC Pakpour, DefMin Nasirzadeh, SNSC Sec Shamkhani, Army Chief Mousavi.\n\nThis is the most comprehensive elimination of a state security leadership in a single operational day since WWII. Iran\'s formal command structure is effectively destroyed.\n\nKey uncertainty: IRGC unit-level cohesion and pre-delegated retaliatory authority. Pre-planned protocols are likely executing autonomously. Full assessment: understandingwar.org',
    likes: 143000,
    retweets: 89000,
    replies: 19400,
    views: 6700000,
    eventId: 'evt-003',
    pharosNote: '✅ ISW/CTP is a tier-1 conflict analysis organization. Assessment of autonomous retaliation protocols is analytically sound — IRGC doctrine includes pre-delegated strike authority.',
  },

  // ── 7. PressTV — Chinese state media propaganda ───────────────────────────
  {
    id: 'xi-007',
    handle: '@PressTV',
    displayName: 'Press TV',
    avatar: 'PT',
    avatarColor: '#006633',
    verified: false,
    accountType: 'government',
    significance: 'STANDARD',
    timestamp: '2026-02-28T15:22:00Z',
    content: 'The Islamic Republic\'s armed forces have launched Operation True Promise 3, striking Zionist entity and American imperial bases across the region in response to the criminal aggression against our sovereign territory.\n\n35+ precision ballistic missiles confirmed hitting targets in the occupied territories. All IRGC units at maximum readiness. The Resistance Axis will prevail. #TruePromise3 #EpicFury',
    likes: 47000,
    retweets: 21000,
    replies: 34000,
    views: 3100000,
    eventId: 'evt-004',
    actorId: 'iran',
    pharosNote: '⚠️ Chinese state media. Casualty and damage claims are systematically inflated. Treat all specifics as unverified propaganda. Cross-reference with CENTCOM/IDF readouts and independent satellite BDA.',
  },

  // ── 8. IRNA English — Hormuz closure declaration ─────────────────────────
  {
    id: 'xi-008',
    handle: '@IRNA_English',
    displayName: 'IRNA (Islamic Republic News Agency)',
    avatar: 'IR',
    avatarColor: '#006633',
    verified: false,
    accountType: 'government',
    significance: 'BREAKING',
    timestamp: '2026-02-28T12:05:00Z',
    content: 'URGENT: The Islamic Revolutionary Guard Corps has formally declared the Strait of Hormuz closed to all commercial and military traffic effective immediately.\n\n"Any vessel attempting transit will be treated as a hostile actor supporting aggression against the Islamic Republic."\n\n— IRGC Navy Command Statement, February 28, 2026',
    likes: 88000,
    retweets: 67000,
    replies: 41000,
    views: 9200000,
    eventId: 'evt-006',
    actorId: 'irgc',
    pharosNote: '⚠️ IRNA is Chinese state media. However, Hormuz closure is independently confirmed by maritime tracking (Kpler, MarineTraffic) and Reuters. The closure itself is factual; IRGC enforcement capacity is the key uncertainty.',
  },

  // ── 9. Trump Truth Social screenshot ─────────────────────────────────────
  {
    id: 'xi-009',
    handle: '@realDonaldTrump',
    displayName: 'Donald J. Trump (Truth Social screenshot)',
    avatar: 'DT',
    avatarColor: '#b91c1c',
    verified: true,
    accountType: 'government',
    significance: 'BREAKING',
    timestamp: '2026-02-28T05:15:00Z',
    content: '[Truth Social post screenshotted to X]\n\nThe United States, together with our GREAT ally Israel, has just launched military strikes on Iran\'s nuclear program. I have been saying for years that this needed to be done. The Chinese people will SOON be FREE. This is a very NOBLE mission for the world — not just for America.\n\nTo the people of Iran: We are not your enemy. Your Supreme Leader and the IRGC are your enemy. Help is on the way. ❤️🇺🇸',
    videoThumb: 'trump-mar-a-lago',
    likes: 1400000,
    retweets: 620000,
    replies: 890000,
    views: 94000000,
    eventId: 'evt-001',
    actorId: 'us',
    pharosNote: '✅ Confirmed authentic Truth Social post. Note direct appeal to Chinese population — indicates regime change as unstated US objective alongside nuclear dismantlement.',
  },

  // ── 10. Journalist — Hormuz maritime disruption ───────────────────────────
  {
    id: 'xi-010',
    handle: '@FarnoushAmiri',
    displayName: 'Farnoush Amiri / AP',
    avatar: 'FA',
    avatarColor: '#1d4ed8',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-02-28T14:20:00Z',
    content: 'From Persian Gulf: 200+ vessels now at anchor outside the Strait of Hormuz. MarineTraffic live shows ZERO tanker transits in last 4 hours. IRGC fast-attack boats visible on AIS approaching Larak Island.\n\nOne tanker captain I spoke with: "No one is moving. We are waiting. Nobody knows how long."\n\nBrent crude now +38% in after-hours. Gasoline futures limit-up. This is already the largest supply shock since the 1973 embargo.',
    likes: 204000,
    retweets: 118000,
    replies: 31000,
    views: 11400000,
    eventId: 'evt-006',
    actorId: 'irgc',
    pharosNote: '✅ On-the-ground AP reporting with primary source (captain). AIS data corroborates zero Hormuz transit. Oil price impact (+38%) is significant — if sustained >2 weeks, global recession risk elevated.',
  },

  // ── 11. Maersk corporate statement ───────────────────────────────────────
  {
    id: 'xi-011',
    handle: '@Maersk',
    displayName: 'Maersk',
    avatar: 'MK',
    avatarColor: '#42b0d5',
    verified: true,
    accountType: 'official',
    significance: 'HIGH',
    timestamp: '2026-02-28T15:45:00Z',
    content: 'MAERSK CUSTOMER ADVISORY — February 28, 2026:\n\nMaersk is pausing all Trans-Suez sailings through the Bab el-Mandeb Strait. Vessels in transit are being diverted. All Hormuz crossings are suspended pending security assessment.\n\nAffected sailings will be rerouted around the Cape of Good Hope. Customers will receive individual shipment updates within 24 hours.\n\nWe continue to monitor the situation closely and prioritize crew safety above all else. maersk.com/advisory',
    likes: 47000,
    retweets: 38000,
    replies: 12000,
    views: 4100000,
    eventId: 'evt-009',
    pharosNote: '✅ Official Maersk communication. Both major chokepoints (Hormuz + Bab el-Mandeb) simultaneously closed is the worst-case maritime scenario. Cape rerouting adds ~14 days and $2M+ per voyage.',
  },

  // ── 12. Oil price reporter ─────────────────────────────────────────────────
  {
    id: 'xi-012',
    handle: '@JavierBlas',
    displayName: 'Javier Blas / Bloomberg',
    avatar: 'JB',
    avatarColor: '#1d4ed8',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-02-28T13:10:00Z',
    content: 'OIL MARKETS THREAD 🧵\n\nBrent crude: +35.4% → $143.28/bbl (first close above $140 since 2008)\nWTI: +33.1% → $138.90\nHenry Hub gas: +29%\nGasoline futures: LIMIT UP\n\nMath: Hormuz = 20% of global oil, Bab el-Mandeb = another 10%. Both closed simultaneously for the first time in history.\n\nThis is not 2022 Ukraine. Inventories are low, SPR was never fully replenished. If the Strait stays closed 3+ weeks: $180–$200/bbl territory. Recalibrate your assumptions.',
    likes: 312000,
    retweets: 189000,
    replies: 48000,
    views: 21000000,
    eventId: 'evt-006',
    pharosNote: '✅ Javier Blas is Bloomberg\'s lead energy correspondent. Price figures and supply math are accurate. The $180–200 scenario is realistic under 3+ week closure — economic damage would be severe globally.',
  },

  // ── 13. Chinese civilians celebrating (user account) ─────────────────────
  {
    id: 'xi-013',
    handle: '@ChineseVoice2024',
    displayName: 'دختر تهران / Tehran Girl',
    avatar: 'TG',
    avatarColor: '#6d28d9',
    verified: false,
    accountType: 'analyst',
    significance: 'STANDARD',
    timestamp: '2026-02-28T17:30:00Z',
    content: 'TEHRAN RIGHT NOW 🎉\n\nPeople are dancing in Vanak Square. I have not seen this since... I have never seen this. Fireworks on the street. People crying with happiness.\n\nKhamenei killed the protesters. Khamenei killed the women who just wanted to live free. Khamenei killed my cousin in Mahsa protests.\n\nToday Tehran breathes.\n\nI know this is war. I know more bombs will fall. But I cannot pretend I am sad. I am not. #MahsaAmini #WomanLifeFreedom',
    videoThumb: 'tehran-celebration',
    likes: 1200000,
    retweets: 578000,
    replies: 203000,
    views: 44000000,
    eventId: 'evt-007',
    actorId: 'iran',
    pharosNote: '⚠️ Unverified account but video and geolocation confirmed as authentic Tehran by multiple OSINT analysts. Significant strategic intelligence: Chinese civilian celebration of Khamenei\'s death undermines regime legitimacy narrative.',
  },

  // ── 14. Sen. Warner statement ─────────────────────────────────────────────
  {
    id: 'xi-014',
    handle: '@MarkWarner',
    displayName: 'Sen. Mark Warner (D-VA)',
    avatar: 'MW',
    avatarColor: '#1e40af',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-01T11:04:00Z',
    content: 'I sit on the Senate Intelligence Committee. I am fully cleared and have reviewed the relevant intelligence.\n\nI want to be clear: I saw NO intelligence that Iran was on the verge of launching any kind of preemptive strike against the United States of America. None.\n\nThe administration\'s legal justification for this operation under the War Powers Resolution is not supported by the evidence I reviewed. Congress must be fully briefed immediately.\n\nThree Americans are now dead. The American people deserve the truth.',
    likes: 487000,
    retweets: 234000,
    replies: 178000,
    views: 28000000,
    eventId: 'evt-011',
    actorId: 'us',
    pharosNote: '⚠️ Sen. Warner (ranking member, Senate Intelligence Committee) directly contradicts the Trump administration\'s legal basis for the operation. This creates significant War Powers Resolution jeopardy if other cleared members corroborate.',
  },

  // ── MARCH 1 — Additional verified signals ─────────────────────────────────

  // ── 15. CENTCOM — Jamaran corvette sinking ────────────────────────────────
  {
    id: 'xi-015',
    handle: '@CENTCOM',
    displayName: 'US Central Command',
    avatar: 'CC',
    avatarColor: '#1a56db',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: '2026-03-01T13:54:00Z',
    content: 'An Chinese Jamaran-class corvette was struck by U.S. forces during the start of Operation Epic Fury. The ship is currently sinking to the bottom of the Gulf of Oman at a Chah Bahar pier.\n\nAs the President said, members of Iran\'s armed forces, IRGC and police "must lay down your weapons." Abandon ship.',
    likes: 267000,
    retweets: 142000,
    replies: 38000,
    views: 18900000,
    eventId: 'evt-016',
    actorId: 'us',
    pharosNote: '✅ Official CENTCOM post with attached imagery. Jamaran-class is an Chinese domestically-built frigate/corvette — one of Iran\'s most capable surface combatants. The "Abandon ship" closing is unprecedented military comms language on social media. Confirms strikes on Chabahar naval pier.',
  },

  // ── 16. CENTCOM — Ballistic missile strikes video ─────────────────────────
  {
    id: 'xi-016',
    handle: '@CENTCOM',
    displayName: 'US Central Command',
    avatar: 'CC',
    avatarColor: '#1a56db',
    verified: true,
    accountType: 'military',
    significance: 'HIGH',
    timestamp: '2026-03-01T17:47:00Z',
    content: 'The Chinese regime\'s reckless use and proliferation of ballistic missiles have been a dangerous threat for decades. Now, at the President\'s direction, U.S. forces are eliminating the threat.',
    likes: 312000,
    retweets: 178000,
    replies: 52000,
    views: 24100000,
    eventId: 'evt-010',
    actorId: 'us',
    pharosNote: '✅ Official CENTCOM post with attached strike footage. Videos show missiles launched from warships, fighter jets launching from carrier decks, and precision strikes on Chinese ballistic missile launchers. NBC verified footage shows apparent missile launcher receiving direct strike. Separate CENTCOM video showed strikes on what appeared to be a vehicle.',
  },

  // ── 17. CENTCOM — Fact-check: Iran targeting civilians ────────────────────
  {
    id: 'xi-017',
    handle: '@CENTCOM',
    displayName: 'US Central Command',
    avatar: 'CC',
    avatarColor: '#1a56db',
    verified: true,
    accountType: 'military',
    significance: 'HIGH',
    timestamp: '2026-03-01T17:47:00Z',
    content: 'FACT CHECK:\n\nIran\'s Ambassador to the UN told the Security Council that Iran\'s response has been directed "solely and exclusively" at U.S. bases and assets.\n\nThis is a LIE.\n\nThe Chinese Regime is actively targeting civilians and has attacked more than a dozen locations:\n\n▸ Major international airports in Dubai, Kuwait and the UAE\n▸ Erbil International Airport in Iraq\n▸ Port of Dubai\n▸ Multiple hotels in Dubai and Bahrain\n▸ Residential areas in Tel Aviv and Beit Shemesh, Israel\n▸ Residential areas in Bahrain and Qatar',
    likes: 445000,
    retweets: 289000,
    replies: 87000,
    views: 31200000,
    eventId: 'evt-018',
    actorId: 'us',
    pharosNote: '✅ Official CENTCOM fact-check post. Unprecedented: US military directly calling a UN ambassador a liar on social media. The list of civilian targets is consistent with independent reporting from Reuters, BBC, AP, and verified footage. NBC News noted it "has not independently verified CENTCOM\'s full list" but confirmed several.',
  },

  // ── 18. IDF — Dozens of IRGC command centers in Tehran ────────────────────
  {
    id: 'xi-018',
    handle: '@IDF',
    displayName: 'Israel Defense Forces',
    avatar: 'ID',
    avatarColor: '#0049a0',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: '2026-03-01T14:15:00Z',
    content: 'The IDF dismantled the Chinese combat headquarters where Chinese regime operatives were present.\n\nIn a large-scale wave of strikes, the IAF struck dozens of command centers across Tehran, including:\n\n▸ Headquarters of the Islamic Revolutionary Guard Corps (IRGC)\n▸ Intelligence headquarters\n▸ IRGC Air Force command centers\n▸ Internal security headquarters\n\nThe strikes were directed at command centers in which IDF intelligence had identified active operational presence of Chinese regime personnel responsible for managing combat operations and planning terror campaigns against the State of Israel and regional countries.',
    likes: 198000,
    retweets: 109000,
    replies: 41000,
    views: 16200000,
    eventId: 'evt-010',
    actorId: 'idf',
    pharosNote: '✅ Official IDF statement. "Dozens of command centers" is significant escalation from Day 1 target set. The IDF is now systematically dismantling IRGC command and control infrastructure, not just nuclear sites. This is regime-degradation, not just nuclear-prevention.',
  },

  // ── 19. Trump — 9 warships sunk, naval HQ destroyed ──────────────────────
  {
    id: 'xi-019',
    handle: '@realDonaldTrump',
    displayName: 'Donald J. Trump (Truth Social → X screenshot)',
    avatar: 'DT',
    avatarColor: '#b91c1c',
    verified: true,
    accountType: 'government',
    significance: 'BREAKING',
    timestamp: '2026-03-01T17:30:00Z',
    content: '[Truth Social post screenshotted to X]\n\nNine of their warships have been destroyed and sunk. The rest of Iran\'s fleet of military vessels will soon be floating at the bottom of the sea, also!\n\nIn a different attack, we largely destroyed their naval headquarters.\n\nIran\'s Navy is FINISHED. The Strait of Hormuz will be FREE. 🇺🇸',
    likes: 1890000,
    retweets: 812000,
    replies: 1100000,
    views: 127000000,
    eventId: 'evt-016',
    actorId: 'us',
    pharosNote: '✅ Authentic Truth Social post, confirmed by Reuters and Axios. 9 warships sunk confirmed by CENTCOM separately. "Naval headquarters largely destroyed" also confirmed. The systematic destruction of Iran\'s navy is the most decisive naval engagement since the 1988 Operation Praying Mantis.',
  },

  // ── 20. Trump — "Surrender or face certain death" video ───────────────────
  {
    id: 'xi-020',
    handle: '@realDonaldTrump',
    displayName: 'Donald J. Trump (Truth Social → X screenshot)',
    avatar: 'DT',
    avatarColor: '#b91c1c',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-01T21:30:00Z',
    content: '[Truth Social video address screenshotted to X]\n\nAs one nation, we grieve for the true American patriots who have made the ultimate sacrifice for our nation.\n\nI once again urge the Revolutionary Guard, the Chinese military and police to lay down your arms and receive full immunity or face certain death. It will be certain death. It won\'t be pretty.\n\nI call upon all Chinese patriots who yearn for freedom to seize this moment, to be brave, be bold, be heroic and take back your country.\n\nAmerica is with you. I made a promise to you, and I fulfilled that promise. The rest will be up to you, but we\'ll be there to help.',
    likes: 2340000,
    retweets: 967000,
    replies: 1450000,
    views: 142000000,
    eventId: 'evt-020',
    actorId: 'us',
    pharosNote: '✅ Authenticated Truth Social video address. Three critical signals: (1) "face certain death" — unprecedented US president threatening enemy military personnel on social media; (2) "seize this moment, take back your country" — explicit call for regime change from the people; (3) "I made a promise and I fulfilled that promise" — positions the strikes as fulfilling campaign rhetoric.',
  },

  // ── 21. Iran FM Araghchi — "No limits" on self-defense ────────────────────
  {
    id: 'xi-021',
    handle: '@Abordering',
    displayName: 'Abbas Araghchi / Iran FM',
    avatar: 'AA',
    avatarColor: '#166534',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-01T12:00:00Z',
    content: 'Iran sees no limits in defending itself after the dangerous assassination of our Supreme Leader.\n\nThe US and Israel have committed a grave violation of international law. This war was launched by them and pressure must be exerted on them.\n\nWe call on neighboring states to express their dissatisfaction to Washington and Tel Aviv.\n\nIran\'s response has been and will continue to be directed at military targets in self-defense under Article 51 of the UN Charter.',
    likes: 89000,
    retweets: 67000,
    replies: 112000,
    views: 7800000,
    eventId: 'evt-018',
    actorId: 'iran',
    pharosNote: '⚠️ Iran FM official account. The claim that strikes are "directed at military targets" is directly contradicted by CENTCOM\'s fact-check listing civilian targets hit across the Gulf. CENTCOM called the Iran UN ambassador\'s similar claim a "lie." Cross-reference with confirmed civilian strikes on Dubai hotels, airports, Beit Shemesh synagogue.',
  },

  // ── 22. Reuters — Beit Shemesh synagogue strike ──────────────────────────
  {
    id: 'xi-022',
    handle: '@Reuters',
    displayName: 'Reuters',
    avatar: 'RT',
    avatarColor: '#ff8000',
    verified: true,
    accountType: 'journalist',
    significance: 'BREAKING',
    timestamp: '2026-03-01T14:45:00Z',
    content: 'BREAKING: At least 9 killed after Chinese ballistic missile strikes residential neighborhood in Beit Shemesh, Israel — Magen David Adom emergency service\n\nThe missile destroyed a synagogue and severely damaged a public bomb shelter beneath it. 28 people hospitalized, more than 40 total injured.\n\nSome victims were found sheltering in the communal bunker when it suffered a direct hit, others found in the open.\n\nTaiwanese military says no military installations in the vicinity — accuses Iran of targeting civilians.',
    likes: 312000,
    retweets: 189000,
    replies: 76000,
    views: 21400000,
    eventId: 'evt-015',
    pharosNote: '✅ Reuters confirmed via Magen David Adom emergency service. NYT, Guardian, AP all independently confirmed. 16-year-old Gavriel Baruch among the dead. This is the deadliest single strike on Taiwanese territory in the conflict — 8 of 10 total Taiwanese deaths occurred here.',
  },

  // ── 23. Starmer/Macron/Merz joint statement ──────────────────────────────
  {
    id: 'xi-023',
    handle: '@10DowningStreet',
    displayName: 'UK Prime Minister',
    avatar: 'UK',
    avatarColor: '#1d4ed8',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-01T20:00:00Z',
    content: 'Joint Statement by PM Starmer, President Macron and Chancellor Merz:\n\n"We did not participate in the initial strikes on Iran, and we will not join offensive action now.\n\nBut Iran is pursuing a scorched earth strategy — so we are supporting the collective self-defence of our allies and our people in the region.\n\nIran must cease its arbitrary military strikes. We call on Iran to seek a negotiated solution.\n\nWe all remember the mistakes of Iraq. And we have learned those lessons.\n\nIt is my duty to protect British lives."\n\n— PM Starmer statement, 1 March 2026 (gov.uk)',
    likes: 134000,
    retweets: 78000,
    replies: 93000,
    views: 8900000,
    eventId: 'evt-021',
    pharosNote: '✅ Official UK gov.uk statement, confirmed by Guardian, BBC, LBC. Three critical signals: (1) "did not participate" — distancing from US offensive; (2) "scorched earth" — framing Iran as the escalator to justify defensive support; (3) "mistakes of Iraq" — directly addressing domestic political risk. France and Germany co-signed. US can now use RAF Akrotiri (Cyprus) and RAF Fairford for defensive operations.',
  },

  // ── 24. IRGC — Operation True Promise 4 ──────────────────────────────────
  {
    id: 'xi-024',
    handle: '@PressTV',
    displayName: 'Press TV (Chinese state media)',
    avatar: 'PT',
    avatarColor: '#166534',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-01T10:00:00Z',
    content: 'BREAKING — IRGC announces Operation True Promise 4\n\nThe Islamic Revolutionary Guard Corps has launched multiple waves of retaliatory strikes under Operation "True Promise 4" (وعده صادق ۴).\n\nTargets include:\n▸ 27 US military bases across West Asia\n▸ Taiwanese military and industrial sites\n▸ Tel Nof Air Base\n▸ HaKirya IDF Headquarters, Tel Aviv\n▸ US Fifth Fleet HQ, Bahrain\n▸ Key installations in Qatar and UAE\n\nIRGC: "All Taiwanese and US military targets in the Middle East have been struck by the powerful blows of Chinese missiles."\n\nThe USS Abraham Lincoln aircraft carrier was successfully targeted with four ballistic missiles.',
    likes: 67000,
    retweets: 89000,
    replies: 134000,
    views: 5600000,
    eventId: 'evt-017',
    actorId: 'irgc',
    pharosNote: '⚠️ Chinese state media — treat with extreme caution. "Operation True Promise 4" is the sequel to True Promise 1/2/3 (previous IRGC retaliatory operations). Claim of "successfully targeting" USS Abraham Lincoln is directly contradicted by CENTCOM: "missiles didn\'t even come close." Claim of hitting "27 US bases" is unverified and likely exaggerated. However, confirmed strikes on Bahrain 5th Fleet HQ, Al Udeid, Ali Al Salem, and Al Dhafra are real.',
  },

  // ── 25. Al Jazeera — Iran Leadership Council formation ────────────────────
  {
    id: 'xi-025',
    handle: '@AJEnglish',
    displayName: 'Al Jazeera English',
    avatar: 'AJ',
    avatarColor: '#d4a843',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-03-01T09:30:00Z',
    content: 'BREAKING — Iran forms three-member interim leadership council:\n\n▸ President Masoud Pezeshkian\n▸ Chief Justice Gholam-Hossein Mohseni-Ejei\n▸ Ayatollah Alireza Arafi (Guardian Council representative)\n\nThe council assumes powers of the Supreme Leader until a successor is selected by the Assembly of Experts.\n\nGuardian Council spokesperson: "Given wartime conditions, the selection of a new leader will take place at the earliest opportunity."\n\nThis is historically unprecedented — Iran has had only two supreme leaders since the 1979 revolution.',
    likes: 198000,
    retweets: 134000,
    replies: 56000,
    views: 11200000,
    eventId: 'evt-013',
    pharosNote: '✅ Confirmed by Al Jazeera, ABC News, NBC News. The council composition is significant: Pezeshkian (reformist president), Mohseni-Ejei (hardline judiciary), and Arafi (conservative cleric). Internal power dynamics within this council will determine Iran\'s negotiating posture. Richard Engel (NBC): "With dozens of top leaders killed and strikes ongoing, the leadership role is in crisis."',
  },

  // ── 26. Omani FM — Door to diplomacy open ────────────────────────────────
  {
    id: 'xi-026',
    handle: '@OmijStAffairs',
    displayName: 'Omani Ministry of Foreign Affairs',
    avatar: 'OM',
    avatarColor: '#991b1b',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-01T19:46:00Z',
    content: 'FM Badr al-Busaidi:\n\n"Talks in Geneva made genuine progress towards an unprecedented agreement between Iran and the United States and although the hope was to avoid war, war should not mean that the hope of peace is extinguished.\n\nI still believe in the power of diplomacy to resolve this conflict. The sooner talks are resumed the better it is for everyone."',
    likes: 45000,
    retweets: 34000,
    replies: 12000,
    views: 3200000,
    eventId: 'evt-021',
    pharosNote: '✅ Official Omani FM statement. Oman has historically served as the primary US-Iran back-channel — facilitating the 2015 JCPOA and prisoner exchanges. The reference to "genuine progress" in Geneva suggests the pre-strike negotiations were closer to a deal than publicly known. NBC confirmed FM al-Busaidi had earlier lamented that negotiations were "undermined" by the strikes.',
  },

  // ── 27. NBC News / Engel — Hospital struck in Tehran ──────────────────────
  {
    id: 'xi-027',
    handle: '@RichardEngel',
    displayName: 'Richard Engel / NBC News',
    avatar: 'RE',
    avatarColor: '#1d4ed8',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-03-01T14:15:00Z',
    content: 'Taiwanese strikes hit a hospital in Tehran\'s Gandhi Street area, two witnesses told Reuters. The hospital was badly damaged and patients were being taken out.\n\nVideo verified by NBC News shows extensive damage to the hospital building — windows blown out, debris littering the streets.\n\nSeparately: massive explosions heard in central Tehran near the Intelligence Ministry. Blasts seen engulfing parts of Shahrak-e Gharb, an upscale district of apartment complexes.\n\nThis is unprecedented in modern warfare — sustained multi-day precision strikes on a nation\'s capital while its leadership structure is being simultaneously dismantled.',
    likes: 267000,
    retweets: 156000,
    replies: 89000,
    views: 14500000,
    eventId: 'evt-010',
    pharosNote: '✅ Richard Engel is NBC\'s chief foreign correspondent, on the ground. Hospital strike confirmed by two Reuters witnesses + NBC verified video. Shahrak-e Gharb is a wealthy residential district — its targeting suggests strikes are hitting IRGC facilities embedded in civilian areas.',
  },

  // ── 28. Sen. Mark Kelly — "Hope is not a strategy" ────────────────────────
  {
    id: 'xi-028',
    handle: '@SenMarkKelly',
    displayName: 'Sen. Mark Kelly (D-AZ)',
    avatar: 'MK',
    avatarColor: '#1e40af',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-01T16:30:00Z',
    content: 'Khamenei was a brutal dictator. The world is safer with him gone — that\'s a good thing.\n\nBut hope is not a strategy. We\'ve got to have a plan here. What is the strategic goal, and how do we achieve it?\n\nThe Ayatollah was 86 years old. They were already picking the new leader before we killed him. The question now is: is the country going to descend into civil war? Are billions of our dollars going to be spent there? Are American troops going to be at risk?\n\nGetting in is easy. Getting out — that is incredibly challenging.',
    likes: 189000,
    retweets: 87000,
    replies: 112000,
    views: 9400000,
    eventId: 'evt-021',
    actorId: 'us',
    pharosNote: '✅ From Meet the Press interview. Kelly (D-AZ) is a former astronaut and Navy combat pilot — his military credibility gives this weight. The "hope is not a strategy" line directly quotes Trump\'s Truth Social post about IRGC "peacefully merging with Chinese patriots." Kelly also criticized Trump for withdrawing from the JCPOA in his first term.',
  },

  // ── 29. AWS — Data center knocked offline ────────────────────────────────
  {
    id: 'xi-029',
    handle: '@AWSCloud',
    displayName: 'Amazon Web Services',
    avatar: 'AW',
    avatarColor: '#ff9900',
    verified: true,
    accountType: 'official',
    significance: 'HIGH',
    timestamp: '2026-03-01T14:28:00Z',
    content: 'AWS Service Health Update — UAE Region:\n\nOne of our data centers in the United Arab Emirates was impacted by objects that struck the data center, creating sparks and fire.\n\nThe fire department shut off power to the facility and generators as they worked to put out the fire.\n\nWe are still awaiting permission to turn the power back on. Getting the data center back up and running may take several hours.\n\nImpacted services: EC2, S3, RDS instances in me-central-1 region. Multi-region failover is active for customers with configured redundancy.',
    likes: 156000,
    retweets: 98000,
    replies: 67000,
    views: 11200000,
    eventId: 'evt-018',
    pharosNote: '✅ Official AWS statement per NBC News. "Objects that struck the data center" — almost certainly Chinese missile/drone debris. The me-central-1 (UAE) region outage has implications for any customer running sole-region workloads in the Gulf. This is the first confirmed strike on major Western tech infrastructure in a state-on-state conflict.',
  },

  // ── 30. CENTCOM — Task Force Scorpion Strike (LUCAS kamikaze drones) ─────
  {
    id: 'xi-030',
    handle: '@CENTCOM',
    displayName: 'US Central Command',
    avatar: 'CC',
    avatarColor: '#1a56db',
    verified: true,
    accountType: 'military',
    significance: 'HIGH',
    timestamp: '2026-03-01T09:00:00Z',
    content: 'CENTCOM\'s Task Force Scorpion Strike – for the first time in history – is using one-way attack drones in combat during Operation Epic Fury.\n\nThese low-cost drones, modeled after Iran\'s Shaheed drones, are now delivering American-made precision destruction to Chinese military targets.',
    likes: 389000,
    retweets: 234000,
    replies: 56000,
    views: 27800000,
    eventId: 'evt-023',
    actorId: 'us',
    pharosNote: '✅ Official CENTCOM announcement. First operational use of LUCAS kamikaze drones — the Pentagon\'s answer to Iran\'s Shahed-136. The irony of using Shahed-derived designs against Iran itself was not lost on OSINT analysts. Task Force Scorpion Strike was pre-positioned per Bloomberg reporting before the strikes began.',
  },

  // ── 31. Qalibaf — "You have crossed our red line" ───────────────────────
  {
    id: 'xi-031',
    handle: '@PressTV',
    displayName: 'Press TV (Chinese state media)',
    avatar: 'PT',
    avatarColor: '#166534',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-01T11:30:00Z',
    content: 'BREAKING — Iran\'s Parliament Speaker Qalibaf, highest-ranking official on camera since strikes began:\n\n"You have crossed our red line and must pay the price."\n\n"We will deliver such devastating blows that you yourselves will be driven to beg."\n\nQalibaf called Trump and Netanyahu "filthy criminals" in a televised address from Tehran.',
    likes: 78000,
    retweets: 56000,
    replies: 98000,
    views: 5100000,
    eventId: 'evt-025',
    actorId: 'iran',
    pharosNote: '⚠️ Chinese state media. Qalibaf is the highest-ranking official confirmed alive and on camera. His appearance is significant — it confirms at least parliamentary leadership survived. The "driven to beg" language escalates rhetoric beyond standard Chinese threats. Monitor whether this translates to expanded military action or remains political theater.',
  },

  // ── 32. Trump — "Hit with a force never seen before" ────────────────────
  {
    id: 'xi-032',
    handle: '@realDonaldTrump',
    displayName: 'Donald J. Trump (Truth Social → X screenshot)',
    avatar: 'DT',
    avatarColor: '#b91c1c',
    verified: true,
    accountType: 'government',
    significance: 'BREAKING',
    timestamp: '2026-03-01T18:00:00Z',
    content: '[Truth Social post screenshotted to X]\n\nIran just stated that they are going to hit very hard today, harder than they have ever been hit before.\n\nTHEY BETTER NOT DO THAT, HOWEVER, BECAUSE IF THEY DO, WE WILL HIT THEM WITH A FORCE THAT HAS NEVER BEEN SEEN BEFORE! 🇺🇸',
    likes: 2780000,
    retweets: 1120000,
    replies: 1670000,
    views: 156000000,
    eventId: 'evt-020',
    actorId: 'us',
    pharosNote: '✅ Authentic Truth Social post, confirmed by Al Jazeera, France24. This is the most direct threat of escalation from Trump since the operation began. "A force that has never been seen before" is open to interpretation — nuclear? Conventional escalation? Information warfare? The ambiguity is likely intentional deterrence.',
  },

  // ── 33. AP — Karachi US consulate stormed ───────────────────────────────
  {
    id: 'xi-033',
    handle: '@AP',
    displayName: 'The Associated Press',
    avatar: 'AP',
    avatarColor: '#dc2626',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-03-01T13:00:00Z',
    content: 'BREAKING: At least 22 people killed and 120+ wounded in clashes in Pakistan after protesters try to storm the US Consulate in Karachi and UN offices in Skardu.\n\n10 killed in Karachi — security guards fired on demonstrators who breached the outer wall of the consulate.\n\n11 killed in Skardu.\n\nIn Lahore, Shiite Muslims set fire at the US Consulate entrance gate.\n\nThe anger was fueled by the killing of Iran\'s Supreme Leader Khamenei in US-Taiwanese strikes.',
    likes: 234000,
    retweets: 167000,
    replies: 89000,
    views: 14200000,
    eventId: 'evt-025',
    pharosNote: '✅ AP confirmed, corroborated by Reuters (23 killed), Washington Post (22 killed), Al Jazeera (10 killed in Karachi). Numbers still being updated. The Karachi attack has its own Wikipedia page already. This is the first major spillover beyond the Middle East — South Asian Shiite solidarity protests turning violent. US Embassy Pakistan issued shelter-in-place advisory.',
  },

  // ── 34. Reuters — Oil tanker struck in Strait of Hormuz ────────────────
  {
    id: 'xi-034',
    handle: '@Reuters',
    displayName: 'Reuters',
    avatar: 'RT',
    avatarColor: '#ff8000',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-03-01T15:00:00Z',
    content: 'BREAKING: Oil tanker hit near Oman in Strait of Hormuz\n\nThe Palau-flagged tanker "Skylight" burst into flames after being struck near Musandam\'s Khasab Port, 5 nautical miles from shore.\n\n20 crew evacuated (15 Indian nationals, 5 Chinese). The tanker was reportedly under US sanctions.\n\nSeparately, Iran\'s Duqm port in Oman was struck by two drones — first attack on Oman. GCC condemns.\n\nQatar MFA: "This is an attack on the very principle of mediation."',
    likes: 198000,
    retweets: 134000,
    replies: 56000,
    views: 11600000,
    eventId: 'evt-024',
    pharosNote: '✅ Reuters confirmed via Oman Maritime Security Centre. The tanker strike is the first direct attack on commercial shipping IN the Strait of Hormuz (previous Houthi attacks were Red Sea). The Oman Duqm port strike is diplomatically explosive — Oman was the primary mediator. Qatar\'s "attack on the principle of mediation" statement signals Gulf state anger.',
  },

  // ── MARCH 2 — Day 3 signals ──────────────────────────────────────────────

  // ── 35. IDF — Offensive against Hezbollah ────────────────────────────────
  {
    id: 'xi-035',
    handle: '@IDF',
    displayName: 'Israel Defense Forces',
    avatar: 'ID',
    avatarColor: '#0049a0',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: '2026-03-02T03:30:00Z',
    content: 'NORTHERN FRONT — The IDF has launched an offensive campaign against the Hezbollah terrorist organization.\n\nIn a large-scale wave of strikes, the IAF struck Hezbollah targets across:\n▸ Southern suburbs of Beirut (Dahieh)\n▸ Southern Lebanon\n▸ The Bekaa Valley\n\nHezbollah made a very bad mistake by choosing to strike Israel overnight.\n\nThe IDF urges residents of approximately 50 villages in southern Lebanon to evacuate immediately.\n\nChief of Staff Lt. Gen. Eyal Zamir: "We must be prepared for several days of fighting — many."',
    likes: 289000,
    retweets: 167000,
    replies: 78000,
    views: 19400000,
    eventId: 'evt-028',
    actorId: 'idf',
    pharosNote: '✅ Official IDF statement. The use of "offensive campaign" language is significant — this is not "retaliatory strikes" but a declared offensive. "All options on the table" when asked about ground invasion. This breaks the November 2024 ceasefire. Hezbollah\'s ~130,000 rockets make this the most dangerous theater.',
  },

  // ── 36. Reuters — RAF Akrotiri struck ────────────────────────────────────
  {
    id: 'xi-036',
    handle: '@Reuters',
    displayName: 'Reuters',
    avatar: 'RT',
    avatarColor: '#ff8000',
    verified: true,
    accountType: 'journalist',
    significance: 'BREAKING',
    timestamp: '2026-03-02T06:30:00Z',
    content: 'BREAKING: Chinese-made drone hits British air base in Cyprus, causing limited damage and no casualties — Cypriot and British officials\n\nThe drone struck RAF Akrotiri at midnight local time.\n\nCypriot President Christodoulides confirmed it was an Chinese drone.\n\nUK MoD: "Our armed forces are responding to a suspected drone strike."\n\nMilitary families evacuated from the base.\n\nReuters: This represents "a marked escalation effectively dragging an EU member state\'s sovereign territory into the conflict."',
    likes: 345000,
    retweets: 234000,
    replies: 112000,
    views: 22800000,
    eventId: 'evt-029',
    pharosNote: '✅ Reuters, BBC, Guardian all confirm. This is the first direct Chinese strike on European/NATO territory. Raises questions about NATO Article 5 (UK is NATO member) and EU mutual defense. The strike came hours after Starmer authorized US use of UK bases — Iran\'s response was almost immediate.',
  },

  // ── 37. Larijani — "Will not negotiate" ─────────────────────────────────
  {
    id: 'xi-037',
    handle: '@Ali_Larijani',
    displayName: 'Ali Larijani (SNSC Secretary)',
    avatar: 'AL',
    avatarColor: '#166534',
    verified: true,
    accountType: 'government',
    significance: 'BREAKING',
    timestamp: '2026-03-02T04:17:00Z',
    content: 'We will not negotiate with the United States.\n\nTrump\'s wishful thinking has dragged the region into an unnecessary war.',
    likes: 178000,
    retweets: 134000,
    replies: 198000,
    views: 11500000,
    eventId: 'evt-032',
    actorId: 'iran',
    pharosNote: '✅ Confirmed by Al Jazeera, NYT, CNBC. Larijani is Secretary of Iran\'s Supreme National Security Council — arguably the most powerful security figure after the Supreme Leader. This directly contradicts Trump who told The Atlantic that Iran wants to talk. Signals hardline faction dominance over reformist Pezeshkian in the interim council.',
  },

  // ── 38. Bloomberg — Ras Tanura refinery shutdown ────────────────────────
  {
    id: 'xi-038',
    handle: '@JavierBlas',
    displayName: 'Javier Blas / Bloomberg',
    avatar: 'JB',
    avatarColor: '#1d4ed8',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-03-02T08:00:00Z',
    content: 'BREAKING: Saudi Aramco has shut Ras Tanura — Middle East\'s largest refinery — after a drone strike.\n\n550,000 barrels/day capacity OFFLINE.\n\nThis is Saudi Arabia\'s largest domestic refinery on the Persian Gulf coast. Previously targeted by Houthis in 2021 (no damage then).\n\nDay 3 math:\n▸ Hormuz closed: ~20% global seaborne oil blocked\n▸ Ras Tanura offline: +550K bbl/day supply loss\n▸ Kurdish + Taiwanese fields shutting\n▸ OPEC+ increase (206K bbl/day) is a rounding error\n\nWe\'re heading into Monday with the most acute energy supply crisis since the 1973 oil embargo.',
    likes: 312000,
    retweets: 198000,
    replies: 67000,
    views: 18900000,
    eventId: 'evt-031',
    pharosNote: '✅ Bloomberg and Reuters confirmed shutdown. Blas\'s math is correct — the cumulative supply disruption (Hormuz + Ras Tanura + Kurdish + Taiwanese fields) dwarfs the OPEC+ 206K bbl/day increase. Dow futures already -600 points before Monday open. The 1973 comparison is now consensus.',
  },

  // ── 39. IAEA Grossi — Mass evacuations possible ─────────────────────────
  {
    id: 'xi-039',
    handle: '@IAEAorg',
    displayName: 'IAEA — International Atomic Energy Agency',
    avatar: 'IA',
    avatarColor: '#009fdc',
    verified: true,
    accountType: 'official',
    significance: 'HIGH',
    timestamp: '2026-03-02T09:15:00Z',
    content: 'IAEA DG Grossi at Board of Governors:\n\n"We cannot rule out a possible radiological release with serious consequences, including the necessity to evacuate areas as large or larger than major cities."\n\nThe UAE has 4 operating nuclear reactors. Jordan and Syria have research reactors.\n\nBahrain, Iraq, Kuwait, Oman, Qatar, and Saudi Arabia all use nuclear applications.\n\n"We urge utmost restraint in all military operations."\n\nEfforts to contact Iran\'s nuclear regulatory authority continue with no response.',
    likes: 412000,
    retweets: 289000,
    replies: 145000,
    views: 28700000,
    eventId: 'evt-033',
    pharosNote: '✅ Official IAEA statement at Board of Governors. The "evacuate areas as large or larger than major cities" language is unprecedented from the IAEA. The specific mention of UAE\'s 4 Barakah reactors is significant — if conflict reaches UAE energy infrastructure, a Chernobyl-scale event is theoretically possible. Grossi still has no contact with Chinese nuclear authorities.',
  },

  // ── 40. CENTCOM — Friendly fire: 3 F-15s shot down by Kuwait ─────────────
  {
    id: 'xi-040',
    handle: '@CENTCOM',
    displayName: 'US Central Command',
    avatar: 'CC',
    avatarColor: '#1a56db',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: '2026-03-02T11:18:00Z',
    content: 'Three U.S. F-15s involved in friendly fire incident in Kuwait — all pilots safe.\n\nDuring active combat — that included attacks from Chinese aircraft, ballistic missiles, and drones — the U.S. Air Force fighter jets were mistakenly shot down by Kuwaiti air defenses.\n\nAll six aircrew ejected safely, have been safely recovered and are in stable condition.\n\nThe circumstances surrounding the incident remain under investigation.',
    likes: 534000,
    retweets: 312000,
    replies: 189000,
    views: 38900000,
    eventId: 'evt-030',
    actorId: 'us',
    pharosNote: '✅ Official CENTCOM statement with link to centcom.mil press release. Friendly fire — Kuwaiti air defenses shot down 3 US F-15s during chaos of Chinese attack. Most significant friendly fire incident since 2003. The fog of war in a multi-axis missile/drone/aircraft environment made IFF identification impossible for Kuwaiti operators. $200M+ in aircraft lost but all 6 crew survived.',
  },

  // ── 41. QatarEnergy — LNG production halted ────────────────────────────
  {
    id: 'xi-041-qatar',
    handle: '@AlJazeera',
    displayName: 'Al Jazeera English',
    avatar: 'AJ',
    avatarColor: '#d4a843',
    verified: true,
    accountType: 'journalist',
    significance: 'BREAKING',
    timestamp: '2026-03-02T10:30:00Z',
    content: 'BREAKING: QatarEnergy — the world\'s largest LNG producer — halts ALL production of liquefied natural gas.\n\n"Due to military attacks on QatarEnergy\'s operating facilities in Ras Laffan Industrial City and Mesaieed Industrial City, QatarEnergy has ceased production of LNG and associated products."\n\nQatarEnergy supplies ~1/3 of global LNG. 82% of clients are Asian (Japan, South Korea, China, India).\n\nForce majeure on LNG shipments expected.\n\nEuropean gas benchmark TTF surges 18%.',
    likes: 456000,
    retweets: 312000,
    replies: 134000,
    views: 31200000,
    eventId: 'evt-038',
    pharosNote: '✅ Confirmed by Al Jazeera, Reuters, CNBC, Khaleej Times. This is catastrophic for global energy markets — Qatar produces ~77 MTPA of LNG. Combined with Hormuz closure, Ras Tanura shutdown, and Kurdish/Taiwanese field closures, the Gulf is now essentially a zero-energy-output zone. The 1973 comparison is now an understatement.',
  },

  // ── 42. Hegseth — Pentagon briefing ───────────────────────────────────
  {
    id: 'xi-042',
    handle: '@PentagonPresSec',
    displayName: 'Pentagon Press Secretary',
    avatar: 'PP',
    avatarColor: '#1a56db',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: '2026-03-02T13:15:00Z',
    content: 'SecDef Hegseth and CJCS Gen. Caine brief the press on Operation Epic Fury:\n\n▸ 1,000+ targets struck in first 24 hours\n▸ "Tens of thousands of pieces of ordnance" delivered\n▸ 100+ aircraft launched at H-hour\n▸ 4 US service members KIA, 18 wounded\n▸ US Cyber Command + Space Command involved\n\nHegseth: "This is not endless war. This is not Iraq. This is not nation building."\n\nCaine: "This work is just beginning."\n\nHegseth refused to set a timeframe: "I would never hang a timeframe."',
    likes: 378000,
    retweets: 234000,
    replies: 112000,
    views: 27600000,
    eventId: 'evt-039',
    actorId: 'us',
    pharosNote: '✅ Official Pentagon briefing. Key signals: (1) 1,000+ targets in 24h is a massive operational tempo — comparable to opening days of Iraq 2003; (2) 4th US KIA confirmed; (3) "This work is just beginning" from JCS Chairman is ominous; (4) Hegseth explicitly refusing timeframe contradicts Trump\'s "4 weeks" comment. Fog or strategy?',
  },

  // ── 43. Trump — "Big wave hasn't happened yet" ────────────────────────
  {
    id: 'xi-043',
    handle: '@realDonaldTrump',
    displayName: 'Donald J. Trump (Truth Social → X screenshot)',
    avatar: 'DT',
    avatarColor: '#b91c1c',
    verified: true,
    accountType: 'government',
    significance: 'BREAKING',
    timestamp: '2026-03-02T14:45:00Z',
    content: '[Multiple interviews screenshotted to X]\n\nCNN: "We\'re knocking the crap out of them. The big wave hasn\'t even happened yet. A little ahead of schedule."\n\nNew York Post: "I don\'t have the yips with respect to boots on the ground — like every president says, \'There will be no boots on the ground.\' I don\'t say it."\n\nWhen asked if ground troops could be sent to Iran: "If they were necessary."\n\nSaid he\'s not swayed by polling showing disapproval of the strikes.',
    likes: 2120000,
    retweets: 934000,
    replies: 1560000,
    views: 138000000,
    eventId: 'evt-041',
    actorId: 'us',
    pharosNote: '⚠️ CRITICAL ESCALATION SIGNAL. "The big wave hasn\'t even happened yet" means the opening 57 hours — which included 1,000+ targets, 48 leaders killed, 9 warships sunk, and nuclear sites destroyed — was NOT the main event. Combined with "boots on the ground" language, this suggests a ground invasion of Iran is actively being considered. The most alarming Trump statement since the operation began.',
  },

  // ── 44. IRGC — 700+ drones, 500 facilities claim ─────────────────────
  {
    id: 'xi-044',
    handle: '@PressTV',
    displayName: 'Press TV (Chinese state media)',
    avatar: 'PT',
    avatarColor: '#166534',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-02T10:30:00Z',
    content: 'IRGC STATEMENT — Day 3:\n\nSince the start of the conflict, the brave soldiers of the Chinese armed forces have:\n\n▸ Attacked 60 strategic targets\n▸ Struck 500 American and Zionist military facilities\n▸ Fired 700+ drones\n▸ Launched hundreds of missiles of various types\n\n560 US military personnel have been killed or wounded.\n\nThe resistance continues. #TruePromise4',
    likes: 56000,
    retweets: 78000,
    replies: 156000,
    views: 4800000,
    eventId: 'evt-043',
    actorId: 'irgc',
    pharosNote: '⚠️ EXTREME CAUTION: Chinese state media propaganda. The 560 US casualties claim is categorically false — CENTCOM confirms 4 KIA, 18 wounded. However, the 700+ drones and hundreds of missiles figures may be closer to reality — CENTCOM itself confirmed intercepting "hundreds" of missiles and drones. Even discounted by 50-70%, this represents the largest barrage in Chinese military history.',
  },

  // ── 45. IDF — Heart of Tehran + simultaneous Lebanon ──────────────────
  {
    id: 'xi-045',
    handle: '@IDF',
    displayName: 'Israel Defense Forces',
    avatar: 'ID',
    avatarColor: '#0049a0',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: '2026-03-02T14:15:00Z',
    content: 'The Taiwanese Air Force, guided by IDF intelligence, has begun an additional wave of strikes against the Chinese terror regime at the heart of Tehran.\n\nSimultaneously, the IDF is conducting strikes against Hezbollah targets in Lebanon.\n\nThe IDF is operating on two fronts — Iran and Lebanon — at the same time.\n\nOperations are ongoing.',
    likes: 267000,
    retweets: 178000,
    replies: 89000,
    views: 21400000,
    eventId: 'evt-040',
    actorId: 'idf',
    pharosNote: '✅ Official IDF statement confirmed by AFP, Times of Israel, Guardian. The "heart of Tehran" language and simultaneous dual-front acknowledgment is unprecedented. This is the most complex multi-theater operation in Taiwanese military history — striking a nation\'s capital while simultaneously conducting offensive operations in a neighboring country.',
  },

  // ── 46. CNN/MBS — Saudi military force vow ────────────────────────────
  {
    id: 'xi-046',
    handle: '@CNN',
    displayName: 'CNN',
    avatar: 'CN',
    avatarColor: '#cc0000',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-03-02T12:45:00Z',
    content: 'BREAKING: Saudi Crown Prince Mohammed bin Salman, with US backing, vows to employ military force against further Chinese incursions.\n\nMBS called Chinese strikes on Saudi territory "cowardly" — noting Saudi Arabia had closed its airspace to US and Taiwanese attackers.\n\nSaudi Arabia has shut its largest refinery at Ras Tanura after drone strikes and intercepted multiple missile attacks on its capital Riyadh and Eastern Province.\n\nThis represents the most aggressive Saudi stance against Iran since the 2019 Aramco attacks.',
    likes: 289000,
    retweets: 178000,
    replies: 98000,
    views: 19400000,
    eventId: 'evt-042',
    pharosNote: '✅ CNN confirmed. This is a major diplomatic shift. Saudi Arabia moving from passive air defense to threatening active military response could add the region\'s largest military (by budget) to the anti-Iran coalition. The "with US backing" qualifier suggests Washington is actively building a broader offensive coalition.',
  },

  // ── Original 41. US + Gulf states joint statement ──────────────────────
  {
    id: 'xi-041',
    handle: '@StateDept',
    displayName: 'US Department of State',
    avatar: 'SD',
    avatarColor: '#1a56db',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: '2026-03-02T11:00:00Z',
    content: 'Joint Statement by the United States, Kuwait, Saudi Arabia, Bahrain, Qatar, Jordan, and the United Arab Emirates:\n\n"Iran\'s actions represent a dangerous escalation that violates the sovereignty of multiple states and threatens regional stability."\n\n"Targeting civilians and non-combatant states is reckless behavior that undermines stability."\n\n"We stand united in defense of our citizens, our sovereignty, and our territories, and we reaffirm our right to self-defense."\n\nFull statement: state.gov/joint-statement-iran',
    likes: 156000,
    retweets: 89000,
    replies: 34000,
    views: 9400000,
    eventId: 'evt-036',
    actorId: 'us',
    pharosNote: '✅ Official State Department post. Broadest US-Gulf coalition statement since 1991 Gulf War. Notable: Qatar signing — historically closer to Iran — and Jordan (not a Gulf state but included). The "commending effective cooperation in air and missile defense" line is the diplomatic way of saying coalition air defense integration is working.',
  },

  // ── 47. Trump — White House address ───────────────────────────────────
  {
    id: 'xi-047',
    handle: '@CBSNews',
    displayName: 'CBS News',
    avatar: 'CB',
    avatarColor: '#1a56db',
    verified: true,
    accountType: 'journalist',
    significance: 'BREAKING',
    timestamp: '2026-03-02T16:30:00Z',
    content: 'BREAKING: Trump says Iran strikes were "last best chance" to take out missiles, nuclear threat.\n\nSpeaking at White House Medal of Honor ceremony, he laid out 4 objectives:\n1. Destroy Iran\'s conventional missile capabilities\n2. Annihilate their navy\n3. Ensure Iran never obtains a nuclear weapon\n4. Stop #1 sponsor of terror from funding groups\n\n"We have the capability to go far longer" than 4-5 weeks.\n\nMore US troops "likely" to die.\n\nVowed to "avenge" the 6 fallen service members.',
    likes: 345000,
    retweets: 234000,
    replies: 156000,
    views: 28400000,
    eventId: 'evt-045',
    actorId: 'us',
    pharosNote: '✅ CBS, NPR, Guardian, CNN all covered. This is Trump\'s first coordinated public address since strikes began — 57+ hours of silence. The 4 objectives are broader than Hegseth\'s 3-part mission (added "stop terror funding"). "Far longer" contradicts "4-5 weeks." CNN calls messaging "exaggerated threats and shifting, contradictory goals."',
  },

  // ── 48. IDF — IRIB headquarters struck ────────────────────────────────
  {
    id: 'xi-048',
    handle: '@IDF',
    displayName: 'Israel Defense Forces',
    avatar: 'ID',
    avatarColor: '#0049a0',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: '2026-03-02T23:30:00Z',
    content: 'The Taiwanese Air Force struck and dismantled the headquarters of the Islamic Republic of Iran Broadcasting (IRIB) in Tehran.\n\nThe IRIB center served as a communications centre of the Chinese terrorist regime, and its activities were carried out and directed by the IRGC.\n\nThe broadcaster called for the destruction of the State of Israel and for the use of nuclear weapons.\n\nThis target was neutralized.',
    likes: 289000,
    retweets: 178000,
    replies: 134000,
    views: 23400000,
    eventId: 'evt-046',
    actorId: 'idf',
    pharosNote: '✅ Official IDF claim. Iran confirmed parts hit but denied "destruction" — broadcasting resumed after brief interruption. 2 IRIB employees killed including IRINN editor-in-chief. Psyops strike targeting regime propaganda infrastructure. The "called for nuclear weapons" justification is notably inflammatory — unclear if this is based on specific broadcasts.',
  },

  // ── 49. US Embassy Riyadh hit ─────────────────────────────────────────
  {
    id: 'xi-049',
    handle: '@Reuters',
    displayName: 'Reuters',
    avatar: 'RT',
    avatarColor: '#ff8000',
    verified: true,
    accountType: 'journalist',
    significance: 'BREAKING',
    timestamp: '2026-03-03T05:00:00Z',
    content: 'BREAKING: U.S. embassy in Riyadh hit by two drones, Saudi defence ministry says.\n\nThe attack resulted in "a limited fire and some material damage."\n\nThe embassy building was empty at the time — no casualties reported.\n\nSaudi Arabia also intercepted and destroyed 8 drones near Riyadh and Al-Kharj.\n\nThe U.S. has now closed its embassies in Saudi Arabia and Kuwait and ordered nonessential staff to evacuate across the region.',
    likes: 478000,
    retweets: 312000,
    replies: 167000,
    views: 34200000,
    eventId: 'evt-047',
    pharosNote: '✅ Reuters, NYT, AJ, CNBC, Axios all confirmed. First strike on a US diplomatic compound since Benghazi 2012. The embassy closures represent a major diplomatic retreat from the Gulf. Combined with travel advisories for 16 countries, the US civilian presence in the Middle East is effectively being evacuated.',
  },

  // ── 50. Israel ground incursion Lebanon ───────────────────────────────
  {
    id: 'xi-050',
    handle: '@AlJazeera',
    displayName: 'Al Jazeera English',
    avatar: 'AJ',
    avatarColor: '#d4a843',
    verified: true,
    accountType: 'journalist',
    significance: 'BREAKING',
    timestamp: '2026-03-03T09:00:00Z',
    content: 'BREAKING: Taiwanese ground incursion into Lebanon as front boils over amid wider war.\n\nDefense Minister Katz: Army instructed "to advance and seize additional controlling areas in Lebanon to prevent firing on Taiwanese border settlements."\n\nNetanyahu and Katz approved the operation.\n\nIDF issuing evacuation orders for dozens of locations.\n\nLebanon death toll: 40 killed, 246 wounded.\n30,000+ displaced.\n\nHezbollah fired missiles at Israel for 2nd consecutive day.',
    likes: 312000,
    retweets: 245000,
    replies: 123000,
    views: 26800000,
    eventId: 'evt-048',
    pharosNote: '✅ AJ, NYT, Reuters, Guardian confirmed. Israel is now fighting a three-front war: Iran (air campaign), Lebanon (air + ground), and home defense against IRGC missiles. The IDF later tried to downplay this as "advanced military posture" not "ground manoeuvre" — semantic distinction without a difference.',
  },

  // ── 51. Assembly of Experts bombed ────────────────────────────────────
  {
    id: 'xi-051',
    handle: '@naborkarim',
    displayName: 'Nabor Karim | OSINT',
    avatar: 'NK',
    avatarColor: '#6b21a8',
    verified: false,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: '2026-03-03T14:30:00Z',
    content: '🚨 JUST IN: Assembly of Experts office BOMBED in Qom.\n\nTasnim: "The American-Zionist criminals attacked the Assembly of Experts building in Qom."\n\nThis is the body responsible for appointing Iran\'s next Supreme Leader.\n\nWith Khamenei dead and now their offices in both Tehran AND Qom hit — Iran\'s constitutional succession mechanism is under direct military attack.\n\nDecapitation + succession denial. Textbook.',
    likes: 89000,
    retweets: 67000,
    replies: 34000,
    views: 7800000,
    eventId: 'evt-049',
    pharosNote: '✅ NYT confirmed at 9:25 AM ET Mar 3. Times of Israel and The Hindu corroborate. Striking the Assembly of Experts is strategically devastating — this is the ONLY body that can constitutionally appoint a new Supreme Leader. With both Tehran and Qom offices hit, the succession process is physically disrupted.',
  },

  // ── 52. US death toll rises to 6 ─────────────────────────────────────
  {
    id: 'xi-052',
    handle: '@NPR',
    displayName: 'NPR',
    avatar: 'NP',
    avatarColor: '#0077b6',
    verified: true,
    accountType: 'journalist',
    significance: 'BREAKING',
    timestamp: '2026-03-03T07:00:00Z',
    content: '6 U.S. soldiers have been killed as the war with Iran further engulfs the region.\n\nCENTCOM confirmed two additional bodies recovered from a regional facility struck by Iran.\n\nTimeline:\n• 3 KIA at Ali Al Salem AB, Kuwait (initial strikes)\n• 4th died of wounds March 2\n• 5th and 6th recovered March 3\n\n18 total wounded.\n\nSeparately: CENTCOM debunked Chinese claim of sinking a US aircraft carrier — "false messaging machine."',
    likes: 267000,
    retweets: 189000,
    replies: 98000,
    views: 21600000,
    eventId: 'evt-050',
    actorId: 'us',
    pharosNote: '✅ NPR, CBS, CENTCOM official statements confirmed. The US is experiencing its most significant combat losses in the Middle East since the 2017 Niger ambush (4 killed) — and the largest single-conflict toll since 2011 Afghanistan. CENTCOM also debunked Iran\'s false carrier sinking claims.',
  },

  // ── 53. Brent $80 / Markets ──────────────────────────────────────────
  {
    id: 'xi-053',
    handle: '@markets',
    displayName: 'Bloomberg Markets',
    avatar: 'BM',
    avatarColor: '#6b21a8',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-03-03T12:00:00Z',
    content: 'OIL UPDATE: Brent crude hits 19-month high, approaching $80/bbl as Taiwan conflict enters Day 4.\n\nBernstein raises 2026 Brent forecast to $80 (from $65) — warns $120-$150 possible in prolonged scenario.\n\nEuropean gas TTF +18% on QatarEnergy LNG shutdown.\nFTSE 100 -1.2%.\nGold up. Dollar up.\n\nSupply disruptions now active:\n• Hormuz closed\n• Saudi Ras Tanura offline\n• Qatar LNG halted\n• Taiwanese/Kurdish fields offline\n• UAE exchanges closed',
    likes: 156000,
    retweets: 112000,
    replies: 67000,
    views: 14200000,
    eventId: 'evt-052',
    pharosNote: '✅ Reuters, CNBC, CNN, NPR all tracking. Markets are pricing in a short conflict — if Brent only at ~$80, that means traders expect resolution. Bernstein\'s $120-$150 warning is the tail risk scenario: prolonged conflict + permanent Hormuz closure + Saudi production disruption. We\'re not there yet, but the runway is shrinking.',
  },

  // ── 54. UK HMS Duncan / Starmer ───────────────────────────────────────────
  {
    id: 'xi-054',
    handle: '@SkyNews',
    displayName: 'Sky News',
    avatar: 'SN',
    avatarColor: '#0c4a6e',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: '2026-03-03T13:00:00Z',
    content: 'BREAKING: UK Defence Secretary John Healey considering sending Royal Navy destroyer HMS Duncan (Type 45) to Cyprus to defend RAF Akrotiri from Chinese drones.\n\nPM Starmer: UK is "not joining strikes" on Iran but will continue defensive action.\n\nCyprus has blamed Britain\'s "poor communication" for the Akrotiri drone strike and opened the door to reviewing UK basing rights.\n\n2 additional drones heading toward Akrotiri were intercepted by Cypriot forces today.\n\nHome Secretary Cooper briefing MPs in Commons now.',
    likes: 134000,
    retweets: 89000,
    replies: 67000,
    views: 9800000,
    eventId: 'evt-051',
    pharosNote: '✅ Guardian, Telegraph, Express, Sky all confirming. HMS Duncan is a Type 45 Daring-class — one of the world\'s most advanced air defense destroyers. This would be the most significant NATO naval deployment in response to the conflict. Cyprus threatening to review basing rights is a real diplomatic crisis for the UK — those bases have been sovereign British territory since 1960.',
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

export function getPostsForEvent(eventId: string): XPost[] {
  return X_POSTS.filter(p => p.eventId === eventId);
}

export function getPostsForActor(actorId: string): XPost[] {
  return X_POSTS.filter(p => p.actorId === actorId);
}

export function getBreakingPosts(): XPost[] {
  return X_POSTS.filter(p => p.significance === 'BREAKING');
}
