import type { XPost, AccountType, SignificanceLevel, PostType } from '@/types/domain';

export const X_POSTS: any[] = [
  {
    id: 'x-tw-001',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000001',
    postType: 'XPOST',
    handle: 'MoNDefense',
    displayName: 'Ministry of National Defense, R.O.C. 🇹🇼',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=MND',
    avatarColor: '#1e3a8a',
    verified: true,
    accountType: 'military',
    significance: 'BREAKING',
    timestamp: new Date('2026-03-01T04:05:00Z'),
    content: 'Multiple PLA missile launches detected from Fujian and Zhejiang. Initial impacts reported near Hsinchu and Ching Chuan Kang Air Bases. National defense protocols activated. Stay in shelters. #TaiwanStrait #ROCMND',
    images: [],
    likes: 12000,
    retweets: 8500,
    replies: 450,
    views: 850000,
    pharosNote: 'Confirms kinetic phase of Joint Sword-2026A. Hypersonic DF-17 usage reported by multiple sensors.',
    actorId: 'taiwan',
    eventId: 'evt-tw-001'
  },
  {
    id: 'x-tw-002',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000002',
    postType: 'XPOST',
    handle: 'GlobalTimesNews',
    displayName: 'Global Times',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=GT',
    avatarColor: '#b91c1c',
    verified: true,
    accountType: 'official',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T04:30:00Z'),
    content: 'The PLA Eastern Theater Command has declared a "Total Exclusion Zone" surrounding the Taiwan region. Any foreign intervention will be met with decisive force. The era of separatist provocations is over. #NationalReunification #PLA',
    images: [],
    likes: 45000,
    retweets: 12000,
    replies: 3500,
    views: 2400000,
    pharosNote: 'Official declaration of maritime and aerial blockade. Direct warning to US 7th Fleet assets.',
    actorId: 'china',
    eventId: 'evt-tw-003'
  },
  {
    id: 'x-tw-003',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000003',
    postType: 'XPOST',
    handle: 'INDOPACOM',
    displayName: 'U.S. Indo-Pacific Command',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=PAC',
    avatarColor: '#1e40af',
    verified: true,
    accountType: 'military',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T06:15:00Z'),
    content: 'INDOPACOM is closely monitoring the unprovoked PLA aggression in the Taiwan Strait. CSG-5 and CSG-7 have been ordered to surge. The US will maintain freedom of navigation and fulfill its commitments under the TRA. #FreeAndOpenIndoPacific',
    images: [],
    likes: 28000,
    retweets: 9000,
    replies: 800,
    views: 1200000,
    pharosNote: 'Official US military response. Confirms deployment of two carrier strike groups.',
    actorId: 'us'
  },
  {
    id: 'x-tw-004',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000004',
    postType: 'XPOST',
    handle: 'PLATracker',
    displayName: 'PLA Tracker (OSINT)',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=PLAT',
    avatarColor: '#454545',
    verified: false,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T04:45:00Z'),
    content: 'SATELLITE INTEL: Commercial imagery shows massive surge of PLAN surface combatants from Ningbo and Zhanjiang. Estimated 40+ vessels now operating in exercise zones surrounding Taiwan. Logistical tail for amphibious landing being prepared in Fujian.',
    images: [],
    likes: 5400,
    retweets: 2100,
    replies: 120,
    views: 450000,
    pharosNote: 'Independent OSINT confirmation of naval mobilization and logistical preparations for potential invasion.',
    actorId: 'china'
  },
  {
    id: 'x-tw-005',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000005',
    postType: 'XPOST',
    handle: 'GordianKnotRay',
    displayName: 'Ray Powell (SeaLight)',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=RP',
    avatarColor: '#0ea5e9',
    verified: true,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T05:30:00Z'),
    content: 'AIS ALERT: Total blackout of commercial AIS signals within the Taiwan Strait. Chinese "Maritime Militia" vessels are effectively acting as a picket line, turning back all container traffic. The blockade is now physical, not just rhetorical.',
    images: [],
    likes: 8900,
    retweets: 3200,
    replies: 210,
    views: 670000,
    pharosNote: 'Confirmation of active maritime militia involvement in enforcing the exclusion zone.',
    actorId: 'china',
    eventId: 'evt-tw-003'
  },
  {
    id: 'x-tw-006',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000006',
    postType: 'XPOST',
    handle: 'TaiwansDefense',
    displayName: 'Taiwan Defense News',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=TDN',
    avatarColor: '#10b981',
    verified: false,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T07:00:00Z'),
    content: 'REPORTS: ROC Army moving Hsiung Feng III anti-ship batteries to coastal positions near Keelung and Hualien. President Lai has authorized "autonomous engagement" for commanders if contact is lost with Taipei. #Taiwan #Defense',
    images: [],
    likes: 15600,
    retweets: 6700,
    replies: 340,
    views: 920000,
    pharosNote: 'Deployment of high-end asymmetric defenses. "Autonomous engagement" order suggests severe concern over C2 continuity.',
    actorId: 'taiwan'
  },
  {
    id: 'x-tw-007',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000007',
    postType: 'XPOST',
    handle: 'Focus_Taiwan',
    displayName: 'Focus Taiwan (CNA English)',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=FTW',
    avatarColor: '#059669',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T08:00:00Z'),
    content: 'Presidential Office confirms "Mountain Shield" protocols active. Leadership has transitioned to hardened command centers. Internet connectivity remains unstable; relying on Starshield/LEO backup systems. #TaiwanCrisis',
    likes: 22000,
    retweets: 11000,
    replies: 1200,
    views: 1500000,
    actorId: 'taiwan'
  },
  {
    id: 'x-tw-008',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000008',
    postType: 'XPOST',
    handle: 'JanesINTEL',
    displayName: 'Janes',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=JANES',
    avatarColor: '#4b5563',
    verified: true,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T04:10:00Z'),
    content: 'ANALYSIS: Initial PLA missile wave prioritized early-warning radar and C2 nodes. DF-17 hypersonic tracks consistent with suppression of Taiwan PAC-3 batteries. This is a highly-rehearsed "Systems Destruction" opening.',
    likes: 12000,
    retweets: 5600,
    replies: 400,
    views: 890000,
    actorId: 'china',
    eventId: 'evt-tw-001'
  },
  {
    id: 'x-tw-009',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000009',
    postType: 'XPOST',
    handle: 'business',
    displayName: 'Bloomberg',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=BBG',
    avatarColor: '#2563eb',
    verified: true,
    accountType: 'journalist',
    significance: 'BREAKING',
    timestamp: new Date('2026-03-01T08:45:00Z'),
    content: 'BREAKING: TSMC halts all chip production in Taiwan as power outages spread and military threat level hits maximum. Global semiconductor supply chain faces "unprecedented" shock.',
    likes: 67000,
    retweets: 34000,
    replies: 5600,
    views: 5600000,
    actorId: 'taiwan',
    eventId: 'evt-tw-004'
  },
  {
    id: 'x-tw-010',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000010',
    postType: 'XPOST',
    handle: 'SCMPNews',
    displayName: 'South China Morning Post',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=SCMP',
    avatarColor: '#facc15',
    verified: true,
    accountType: 'journalist',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T09:30:00Z'),
    content: 'Beijing announces total ban on rare earth exports to "all nations participating in the illegal containment of China." Export controls effective immediately. #China #Sanctions',
    likes: 31000,
    retweets: 14000,
    replies: 2800,
    views: 2100000,
    actorId: 'china'
  },
  {
    id: 'x-tw-011',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000011',
    postType: 'XPOST',
    handle: 'NetBlocks',
    displayName: 'NetBlocks',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=NB',
    avatarColor: '#333333',
    verified: true,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T05:45:00Z'),
    content: '⚠️ Confirmed: Major government websites in Taiwan, including the Presidential Office and MoD, are currently unreachable. Network telemetry shows massive DDoS traffic patterns. #Taiwan #CyberAttack',
    likes: 8200,
    retweets: 4100,
    replies: 150,
    views: 520000,
    eventId: 'evt-tw-006'
  },
  {
    id: 'x-tw-012',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000012',
    postType: 'XPOST',
    handle: 'duandang',
    displayName: 'Duan Dang',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=DD',
    avatarColor: '#0f172a',
    verified: true,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T12:00:00Z'),
    content: 'Reports emerging of a significant naval skirmish near Penghu. Unconfirmed footage shows a ROCN corvette trailing heavy smoke. PLAN Type 052D presence confirmed in the area. Escalation is moving fast. #TaiwanStrait',
    likes: 12500,
    retweets: 5800,
    replies: 340,
    views: 980000,
    actorId: 'china',
    eventId: 'evt-tw-007'
  },
  {
    id: 'x-tw-013',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000013',
    postType: 'XPOST',
    handle: 'jointstaffpa',
    displayName: 'Japan Joint Staff',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=JJS',
    avatarColor: '#4c1d95',
    verified: true,
    accountType: 'military',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T14:15:00Z'),
    content: 'The JASDF has scrambled F-15J aircraft from Naha Air Base in response to multiple PLA incursions into Japan\'s ADIZ. PAC-3 units are being repositioned to the Sakishima Islands. #JSDF #DefendJapan',
    likes: 34000,
    retweets: 12000,
    replies: 800,
    views: 1800000,
    actorId: 'japan',
    eventId: 'evt-tw-008'
  },
  {
    id: 'x-tw-014',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000014',
    postType: 'XPOST',
    handle: 'US7thFleet',
    displayName: 'U.S. 7th Fleet',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=7F',
    avatarColor: '#1e3a8a',
    verified: true,
    accountType: 'military',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T15:00:00Z'),
    content: 'USS George Washington (CVN 73) and escort ships have departed Yokosuka. The 7th Fleet remains committed to a free and open Indo-Pacific. #PresenceMatters #OperationFormosaShield',
    likes: 42000,
    retweets: 15000,
    replies: 1200,
    views: 2500000,
    actorId: 'us'
  },
  {
    id: 'x-tw-015',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000015',
    postType: 'XPOST',
    handle: 'UN_News',
    displayName: 'UN News',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=UN',
    avatarColor: '#0369a1',
    verified: true,
    accountType: 'official',
    significance: 'STANDARD',
    timestamp: new Date('2026-03-01T20:30:00Z'),
    content: 'Emergency Security Council session on the situation in the Taiwan Strait concludes without resolution following use of veto by two permanent members. Secretary-General calls for "maximum restraint."',
    likes: 15000,
    retweets: 7000,
    replies: 2500,
    views: 1100000,
    eventId: 'evt-tw-010'
  },
  {
    id: 'x-tw-016',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000016',
    postType: 'XPOST',
    handle: 'shugilla2',
    displayName: 'Shugilla (OSINT)',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=SH',
    avatarColor: '#111827',
    verified: true,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T04:50:00Z'),
    content: 'IMAGERY: Direct hit on the hardened early-warning radar facility at Leshan Mountain. Secondary explosions suggest high-explosive payloads. ROC defense capabilities in the north significantly degraded.',
    likes: 9500,
    retweets: 4200,
    replies: 210,
    views: 780000,
    actorId: 'china',
    eventId: 'evt-tw-001'
  },
  {
    id: 'x-tw-017',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000017',
    postType: 'XPOST',
    handle: 'MOFA_Taiwan',
    displayName: 'Ministry of Foreign Affairs 🇹🇼',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=MOFA',
    avatarColor: '#1e40af',
    verified: true,
    accountType: 'government',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T10:15:00Z'),
    content: 'We thank our G7 partners for their strong support. The global community must realize that an attack on Taiwan is an attack on the global economy and democratic values. #StandWithTaiwan',
    likes: 28000,
    retweets: 13000,
    replies: 900,
    views: 1400000,
    actorId: 'taiwan',
    eventId: 'evt-tw-005'
  },
  {
    id: 'x-tw-018',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000018',
    postType: 'XPOST',
    handle: 'Alert5',
    displayName: 'Alert 5',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=A5',
    avatarColor: '#b91c1c',
    verified: false,
    accountType: 'analyst',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T07:30:00Z'),
    content: 'NOTAM ALERT: Total closure of Taipei FIR. Commercial air traffic effectively halted. PLA Air Force J-20s and KJ-500s establishing a permanent CAP across the median line. Strait is a total no-fly zone.',
    likes: 11000,
    retweets: 5200,
    replies: 180,
    views: 820000,
    actorId: 'china'
  },
  {
    id: 'x-tw-019',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000019',
    postType: 'XPOST',
    handle: 'DaveyAlba',
    displayName: 'Davey Alba',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=DA',
    avatarColor: '#0ea5e9',
    verified: true,
    accountType: 'journalist',
    significance: 'STANDARD',
    timestamp: new Date('2026-03-01T17:00:00Z'),
    content: 'Scene at Taoyuan Airport is chaotic. Thousands trying to leave, but no planes are taking off. Security is tight, and rumors of impending missile strikes are causing panic. Backup power is failing. #Taiwan',
    likes: 7600,
    retweets: 3100,
    replies: 450,
    views: 610000,
    eventId: 'evt-tw-009'
  },
  {
    id: 'x-tw-020',
    conflictId: 'taiwan-2026',
    tweetId: '1763400000000000020',
    postType: 'XPOST',
    handle: 'MNDTaiwan',
    displayName: 'Ministry of National Defense, R.O.C. 🇹🇼',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=MND',
    avatarColor: '#1e3a8a',
    verified: true,
    accountType: 'military',
    significance: 'HIGH',
    timestamp: new Date('2026-03-01T22:00:00Z'),
    content: 'End of Day 1 SitRep: ROC forces remain in high readiness. Despite severe kinetic and cyber pressure, our defensive architecture is intact. We continue to track all PLA movements. Democracy will prevail.',
    likes: 56000,
    retweets: 24000,
    replies: 3200,
    views: 3800000,
    actorId: 'taiwan'
  }
];
