import type { ActivityLevel, Stance, Actor } from '@/types/domain';

export const ACTORS: Actor[] = [
  {
    id: 'us',
    name: 'United States',
    fullName: 'United States — INDOPACOM',
    countryCode: 'us',
    type: 'STATE',
    activityLevel: 'CRITICAL',
    activityScore: 95,
    stance: 'DEFENDER',
    saying: '"The United States will honor its commitments under the Taiwan Relations Act. We will not stand by while the freedom of the Pacific is threatened by illegal blockades and unprovoked aggression. Operation Formosa Shield is a defensive necessity." — President Trump, Oval Office Address, March 1, 2026',
    doing: [
      'Deploying Carrier Strike Groups 5 and 7 to the Philippine Sea and Luzon Strait.',
      'Activating the "Pacific Deterrence Initiative" surge protocols.',
      'Providing real-time satellite intelligence and tactical data-link support to Taiwan\'s military.',
      'Coordinating with Japan and Australia on maritime patrol and anti-submarine warfare.',
      'Enforcing a counter-blockade on Chinese energy imports through the Strait of Malacca.',
    ],
    assessment: 'The US is walking a fine line between effective deterrence and full-scale kinetic involvement. The deployment of two CSGs is a clear signal of intent, but the administration has yet to authorize strikes on mainland Chinese territory. Internal debate in Washington centers on the "porcupine strategy" and whether to provide direct air cover over Taiwan.',
    recentActions: [
      { date: '2026-03-01', type: 'MILITARY',   description: 'Activated Operation Formosa Shield; CSG-5 redirected from Yokosuka', verified: true,  significance: 'HIGH' },
      { date: '2026-03-01', type: 'DIPLOMATIC', description: 'Issued formal ultimatum to Beijing to cease blockade operations', verified: true,  significance: 'HIGH' },
      { date: '2026-02-28', type: 'INTELLIGENCE', description: 'Detected massive PLA mobilization in Fujian province', verified: true,  significance: 'MEDIUM' },
    ],
    keyFigures: ['President Donald Trump', 'SecDef Pete Hegseth', 'INDOPACOM Adm. Samuel Paparo'],
    linkedEventIds: ['evt-tw-001', 'evt-tw-004'],
    daySnapshots: {
      '2026-03-01': {
        activityLevel: 'CRITICAL',
        activityScore: 95,
        stance: 'DEFENDER',
        saying: '"The United States will honor its commitments. Operation Formosa Shield has begun." — President Trump',
        doing: [
          'CSG-5 and CSG-7 moving to intercept positions.',
          'Intelligence sharing with Taipei at maximum tier.',
          'Diplomatic mobilization of G7 and Quad partners.',
        ],
        assessment: 'Day 1 focused on signaling and rapid deployment. The US has moved to secure the "Second Island Chain" and is testing Chinese resolve in the Luzon Strait.',
      },
    },
  },
  {
    id: 'china',
    name: 'China',
    fullName: 'People\'s Republic of China — PLA',
    countryCode: 'cn',
    type: 'STATE',
    activityLevel: 'CRITICAL',
    activityScore: 98,
    stance: 'AGGRESSOR',
    saying: '"Taiwan is an inalienable part of China. Joint Sword-2026A is a necessary and legitimate response to the provocations of separatist forces and foreign interference. No one should underestimate the resolve of the Chinese people to defend our national sovereignty." — President Xi Jinping, March 1, 2026',
    doing: [
      'Enforcing a Total Exclusion Zone around Taiwan using the PLAN and Maritime Militia.',
      'Conducting "saturated" missile strikes on Taiwanese critical infrastructure.',
      'Executing high-intensity cyber-warfare against Taiwan\'s financial and energy sectors.',
      'Deploying J-20 stealth fighters to establish air superiority over the Taiwan Strait.',
      'Threatening "countermeasures" against any third-party intervention.',
    ],
    assessment: 'China has committed to a "Quick Strike, Hard Blockade" strategy. The objective is to force a Taiwanese surrender before US reinforcements can arrive in force. The use of DF-17 hypersonic missiles in the opening wave indicates a desire to demonstrate technical superiority and deter US carrier intervention.',
    recentActions: [
      { date: '2026-03-01', type: 'MILITARY',   description: 'Launched Joint Sword-2026A; declared Total Exclusion Zone', verified: true,  significance: 'HIGH' },
      { date: '2026-03-01', type: 'POLITICAL',  description: 'Suspended all diplomatic communication with Washington and Taipei', verified: true,  significance: 'HIGH' },
      { date: '2026-03-01', type: 'ECONOMIC',   description: 'Banned export of semiconductors and rare earths to "hostile" states', verified: true,  significance: 'HIGH' },
    ],
    keyFigures: ['President Xi Jinping', 'Gen. Zhang Youxia', 'Adm. Hu Zhongming'],
    linkedEventIds: ['evt-tw-001', 'evt-tw-002', 'evt-tw-003'],
    daySnapshots: {
      '2026-03-01': {
        activityLevel: 'CRITICAL',
        activityScore: 98,
        stance: 'AGGRESSOR',
        saying: '"National reunification is the inevitable trend of history." — Xi Jinping',
        doing: [
          'Blockade zones established in six sectors.',
          'Cyber-kinetic strike on Taiwan power grid.',
          'DF-15/17 missile barrage on military airfields.',
        ],
        assessment: 'Day 1 was a high-intensity demonstration of power. China successfully severed Taiwan\'s physical and digital connections to the world, creating a "Strategic Vacuum."',
      },
    },
  },
  {
    id: 'taiwan',
    name: 'Taiwan',
    fullName: 'Republic of China (Taiwan) — ROC Armed Forces',
    countryCode: 'tw',
    type: 'STATE',
    activityLevel: 'CRITICAL',
    activityScore: 92,
    stance: 'DEFENDER',
    saying: '"Taiwan will not bow to intimidation. We will defend our democracy, our freedom, and our way of life. Every citizen is a defender of our home. We call on the international community to stand with Taiwan against this blatant aggression." — President Lai Ching-te, March 1, 2026',
    doing: [
      'Activating the Overall Defense Concept (ODC) for asymmetric warfare.',
      'Deploying mobile anti-ship missile batteries (Hsiung Feng III) to coastal regions.',
      'Dispersing air assets to hardened mountain hangars and civilian highway strips.',
      'Distributing weapons and supplies to civilian defense units.',
      'Maintaining emergency satellite communications via low-earth orbit constellations.',
    ],
    assessment: 'Taiwan\'s strategy is "Resilience through Dispersion." By avoiding decisive fleet-on-fleet battles and focusing on mobile, lethal defenses, they aim to make an invasion prohibitively costly for the PLA. The main challenge is the energy and food blockade, which could become critical within weeks.',
    recentActions: [
      { date: '2026-03-01', type: 'POLITICAL',  description: 'Declared national state of emergency and martial law', verified: true,  significance: 'HIGH' },
      { date: '2026-03-01', type: 'MILITARY',   description: 'Activated all reserve forces (approx. 1.5 million personnel)', verified: true,  significance: 'HIGH' },
      { date: '2026-03-01', type: 'DIPLOMATIC', description: 'Requested emergency assistance from G7 and the UN', verified: true,  significance: 'MEDIUM' },
    ],
    keyFigures: ['President Lai Ching-te', 'Adm. Mei Chia-shu'],
    linkedEventIds: ['evt-tw-001', 'evt-tw-003'],
    daySnapshots: {
      '2026-03-01': {
        activityLevel: 'CRITICAL',
        activityScore: 92,
        stance: 'DEFENDER',
        saying: '"We will defend our home." — President Lai Ching-te',
        doing: [
          'Mobile missile batteries deployed.',
          'Underground command centers activated.',
          'Civilian evacuation from coastal hotspots.',
        ],
        assessment: 'Day 1 focused on survival and transition to a war footing. Despite the blackout, the ROC military remains intact and has successfully transitioned to mobile operations.',
      },
    },
  },
];
